# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('include_content', wagtail.wagtailcore.blocks.CharBlock()), ('content_list', wagtail.wagtailcore.blocks.CharBlock())), blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Content updated date')),
            ],
            options={
                'ordering': ('date',),
            },
            bases=('wagtailcore.page',),
        ),
    ]
